# Generated by Django 4.1.9 on 2023-06-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=120, unique=True)),
                ("paid", models.BooleanField(default=False)),
                ("scenarios", models.CharField(max_length=100)),
                ("frequency", models.CharField(max_length=10)),
                ("brand", models.CharField(max_length=100)),
            ],
        ),
    ]
